FROM golang:1-bookworm

WORKDIR /app

RUN apt update \
    && apt install -y protobuf-compiler

COPY go.mod go.sum ./

RUN go mod download \
    && go install github.com/volatiletech/sqlboiler/v4@latest \
    && go install github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-psql@latest \
    && go install google.golang.org/protobuf/cmd/protoc-gen-go@latest \
    && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
