// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testPrefs(t *testing.T) {
	t.Parallel()

	query := Prefs()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testPrefsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Pref{}
	if err = randomize.Struct(seed, o, prefDBTypes, true, prefColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pref struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Prefs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPrefsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Pref{}
	if err = randomize.Struct(seed, o, prefDBTypes, true, prefColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pref struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Prefs().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Prefs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPrefsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Pref{}
	if err = randomize.Struct(seed, o, prefDBTypes, true, prefColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pref struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PrefSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Prefs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPrefsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Pref{}
	if err = randomize.Struct(seed, o, prefDBTypes, true, prefColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pref struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := PrefExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Pref exists: %s", err)
	}
	if !e {
		t.Errorf("Expected PrefExists to return true, but got false.")
	}
}

func testPrefsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Pref{}
	if err = randomize.Struct(seed, o, prefDBTypes, true, prefColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pref struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	prefFound, err := FindPref(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if prefFound == nil {
		t.Error("want a record, got nil")
	}
}

func testPrefsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Pref{}
	if err = randomize.Struct(seed, o, prefDBTypes, true, prefColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pref struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Prefs().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testPrefsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Pref{}
	if err = randomize.Struct(seed, o, prefDBTypes, true, prefColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pref struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Prefs().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testPrefsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	prefOne := &Pref{}
	prefTwo := &Pref{}
	if err = randomize.Struct(seed, prefOne, prefDBTypes, false, prefColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pref struct: %s", err)
	}
	if err = randomize.Struct(seed, prefTwo, prefDBTypes, false, prefColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pref struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = prefOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = prefTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Prefs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testPrefsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	prefOne := &Pref{}
	prefTwo := &Pref{}
	if err = randomize.Struct(seed, prefOne, prefDBTypes, false, prefColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pref struct: %s", err)
	}
	if err = randomize.Struct(seed, prefTwo, prefDBTypes, false, prefColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pref struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = prefOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = prefTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Prefs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func prefBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Pref) error {
	*o = Pref{}
	return nil
}

func prefAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Pref) error {
	*o = Pref{}
	return nil
}

func prefAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Pref) error {
	*o = Pref{}
	return nil
}

func prefBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Pref) error {
	*o = Pref{}
	return nil
}

func prefAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Pref) error {
	*o = Pref{}
	return nil
}

func prefBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Pref) error {
	*o = Pref{}
	return nil
}

func prefAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Pref) error {
	*o = Pref{}
	return nil
}

func prefBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Pref) error {
	*o = Pref{}
	return nil
}

func prefAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Pref) error {
	*o = Pref{}
	return nil
}

func testPrefsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Pref{}
	o := &Pref{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, prefDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Pref object: %s", err)
	}

	AddPrefHook(boil.BeforeInsertHook, prefBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	prefBeforeInsertHooks = []PrefHook{}

	AddPrefHook(boil.AfterInsertHook, prefAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	prefAfterInsertHooks = []PrefHook{}

	AddPrefHook(boil.AfterSelectHook, prefAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	prefAfterSelectHooks = []PrefHook{}

	AddPrefHook(boil.BeforeUpdateHook, prefBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	prefBeforeUpdateHooks = []PrefHook{}

	AddPrefHook(boil.AfterUpdateHook, prefAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	prefAfterUpdateHooks = []PrefHook{}

	AddPrefHook(boil.BeforeDeleteHook, prefBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	prefBeforeDeleteHooks = []PrefHook{}

	AddPrefHook(boil.AfterDeleteHook, prefAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	prefAfterDeleteHooks = []PrefHook{}

	AddPrefHook(boil.BeforeUpsertHook, prefBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	prefBeforeUpsertHooks = []PrefHook{}

	AddPrefHook(boil.AfterUpsertHook, prefAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	prefAfterUpsertHooks = []PrefHook{}
}

func testPrefsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Pref{}
	if err = randomize.Struct(seed, o, prefDBTypes, true, prefColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pref struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Prefs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPrefsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Pref{}
	if err = randomize.Struct(seed, o, prefDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Pref struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(prefColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Prefs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPrefsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Pref{}
	if err = randomize.Struct(seed, o, prefDBTypes, true, prefColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pref struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPrefsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Pref{}
	if err = randomize.Struct(seed, o, prefDBTypes, true, prefColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pref struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PrefSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPrefsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Pref{}
	if err = randomize.Struct(seed, o, prefDBTypes, true, prefColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pref struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Prefs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	prefDBTypes = map[string]string{`ID`: `bigint`, `Code`: `character varying`, `Region`: `character varying`, `Name`: `character varying`, `IsCrawl`: `boolean`, `CreatedAt`: `timestamp without time zone`, `UpdatedAt`: `timestamp without time zone`}
	_           = bytes.MinRead
)

func testPrefsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(prefPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(prefAllColumns) == len(prefPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Pref{}
	if err = randomize.Struct(seed, o, prefDBTypes, true, prefColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pref struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Prefs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, prefDBTypes, true, prefPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Pref struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testPrefsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(prefAllColumns) == len(prefPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Pref{}
	if err = randomize.Struct(seed, o, prefDBTypes, true, prefColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pref struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Prefs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, prefDBTypes, true, prefPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Pref struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(prefAllColumns, prefPrimaryKeyColumns) {
		fields = prefAllColumns
	} else {
		fields = strmangle.SetComplement(
			prefAllColumns,
			prefPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := PrefSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testPrefsUpsert(t *testing.T) {
	t.Parallel()

	if len(prefAllColumns) == len(prefPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Pref{}
	if err = randomize.Struct(seed, &o, prefDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Pref struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Pref: %s", err)
	}

	count, err := Prefs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, prefDBTypes, false, prefPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Pref struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Pref: %s", err)
	}

	count, err = Prefs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
