// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: pkg/proto/rooms.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRoomsByPrefCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrefCode string `protobuf:"bytes,1,opt,name=pref_code,json=prefCode,proto3" json:"pref_code,omitempty"`
}

func (x *GetRoomsByPrefCodeRequest) Reset() {
	*x = GetRoomsByPrefCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_rooms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomsByPrefCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomsByPrefCodeRequest) ProtoMessage() {}

func (x *GetRoomsByPrefCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rooms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomsByPrefCodeRequest.ProtoReflect.Descriptor instead.
func (*GetRoomsByPrefCodeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rooms_proto_rawDescGZIP(), []int{0}
}

func (x *GetRoomsByPrefCodeRequest) GetPrefCode() string {
	if x != nil {
		return x.PrefCode
	}
	return ""
}

type Room struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrefCode  string `protobuf:"bytes,1,opt,name=pref_code,json=prefCode,proto3" json:"pref_code,omitempty"`
	HouseCode string `protobuf:"bytes,2,opt,name=house_code,json=houseCode,proto3" json:"house_code,omitempty"`
	RoomCode  string `protobuf:"bytes,3,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	PrefName  string `protobuf:"bytes,4,opt,name=pref_name,json=prefName,proto3" json:"pref_name,omitempty"`
	HouseName string `protobuf:"bytes,5,opt,name=house_name,json=houseName,proto3" json:"house_name,omitempty"`
	Status    string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Price     int32  `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	Fee       int32  `protobuf:"varint,8,opt,name=fee,proto3" json:"fee,omitempty"`
	Type      string `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
	Space     int32  `protobuf:"varint,10,opt,name=space,proto3" json:"space,omitempty"`
	Floor     int32  `protobuf:"varint,11,opt,name=floor,proto3" json:"floor,omitempty"`
	LayoutUrl string `protobuf:"bytes,12,opt,name=layout_url,json=layoutUrl,proto3" json:"layout_url,omitempty"`
	Url       string `protobuf:"bytes,13,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *Room) Reset() {
	*x = Room{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_rooms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rooms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rooms_proto_rawDescGZIP(), []int{1}
}

func (x *Room) GetPrefCode() string {
	if x != nil {
		return x.PrefCode
	}
	return ""
}

func (x *Room) GetHouseCode() string {
	if x != nil {
		return x.HouseCode
	}
	return ""
}

func (x *Room) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *Room) GetPrefName() string {
	if x != nil {
		return x.PrefName
	}
	return ""
}

func (x *Room) GetHouseName() string {
	if x != nil {
		return x.HouseName
	}
	return ""
}

func (x *Room) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Room) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Room) GetFee() int32 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Room) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Room) GetSpace() int32 {
	if x != nil {
		return x.Space
	}
	return 0
}

func (x *Room) GetFloor() int32 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *Room) GetLayoutUrl() string {
	if x != nil {
		return x.LayoutUrl
	}
	return ""
}

func (x *Room) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetRoomsByPrefCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms []*Room `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
}

func (x *GetRoomsByPrefCodeResponse) Reset() {
	*x = GetRoomsByPrefCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_rooms_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomsByPrefCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomsByPrefCodeResponse) ProtoMessage() {}

func (x *GetRoomsByPrefCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rooms_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomsByPrefCodeResponse.ProtoReflect.Descriptor instead.
func (*GetRoomsByPrefCodeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rooms_proto_rawDescGZIP(), []int{2}
}

func (x *GetRoomsByPrefCodeResponse) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

var File_pkg_proto_rooms_proto protoreflect.FileDescriptor

var file_pkg_proto_rooms_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x6f, 0x6d,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x22, 0x38,
	0x0a, 0x19, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x42, 0x79, 0x50, 0x72, 0x65, 0x66,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x72, 0x65, 0x66, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x72, 0x65, 0x66, 0x43, 0x6f, 0x64, 0x65, 0x22, 0xcc, 0x02, 0x0a, 0x04, 0x52, 0x6f, 0x6f,
	0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x66, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x65, 0x66, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72,
	0x65, 0x66, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x72, 0x65, 0x66, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x6f, 0x75, 0x73, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x66, 0x65, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x61, 0x79, 0x6f,
	0x75, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x3f, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x52, 0x6f,
	0x6f, 0x6d, 0x73, 0x42, 0x79, 0x50, 0x72, 0x65, 0x66, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x2e, 0x52, 0x6f, 0x6f,
	0x6d, 0x52, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x32, 0x68, 0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x6d,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x59, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x52, 0x6f,
	0x6f, 0x6d, 0x73, 0x42, 0x79, 0x50, 0x72, 0x65, 0x66, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x2e,
	0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x42, 0x79,
	0x50, 0x72, 0x65, 0x66, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73,
	0x42, 0x79, 0x50, 0x72, 0x65, 0x66, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_rooms_proto_rawDescOnce sync.Once
	file_pkg_proto_rooms_proto_rawDescData = file_pkg_proto_rooms_proto_rawDesc
)

func file_pkg_proto_rooms_proto_rawDescGZIP() []byte {
	file_pkg_proto_rooms_proto_rawDescOnce.Do(func() {
		file_pkg_proto_rooms_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_rooms_proto_rawDescData)
	})
	return file_pkg_proto_rooms_proto_rawDescData
}

var file_pkg_proto_rooms_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_rooms_proto_goTypes = []interface{}{
	(*GetRoomsByPrefCodeRequest)(nil),  // 0: rooms.GetRoomsByPrefCodeRequest
	(*Room)(nil),                       // 1: rooms.Room
	(*GetRoomsByPrefCodeResponse)(nil), // 2: rooms.GetRoomsByPrefCodeResponse
}
var file_pkg_proto_rooms_proto_depIdxs = []int32{
	1, // 0: rooms.GetRoomsByPrefCodeResponse.rooms:type_name -> rooms.Room
	0, // 1: rooms.RoomService.GetRoomsByPrefCode:input_type -> rooms.GetRoomsByPrefCodeRequest
	2, // 2: rooms.RoomService.GetRoomsByPrefCode:output_type -> rooms.GetRoomsByPrefCodeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_rooms_proto_init() }
func file_pkg_proto_rooms_proto_init() {
	if File_pkg_proto_rooms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_rooms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomsByPrefCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_rooms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Room); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_rooms_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomsByPrefCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_rooms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_rooms_proto_goTypes,
		DependencyIndexes: file_pkg_proto_rooms_proto_depIdxs,
		MessageInfos:      file_pkg_proto_rooms_proto_msgTypes,
	}.Build()
	File_pkg_proto_rooms_proto = out.File
	file_pkg_proto_rooms_proto_rawDesc = nil
	file_pkg_proto_rooms_proto_goTypes = nil
	file_pkg_proto_rooms_proto_depIdxs = nil
}
